language: node_js
node_js: 8
script:
    - npm run build
deploy:
    - provider: npm
      email: bryphe@outlook.com
      skip_cleanup: true
      api_key:
          secure: ZyK8uVorIULWirekZSTko1bE8TTZLkw2kYKeoxL2m6tbeyO+bbuxiT0FXxI3jd1r/+BQLAZlmLP1XP8jmbU6gQW/EbPN7y3CbwUO6NqooA36/Osv3uA6X4abVuo+JeV5SD0wR36JI3WkXAQz9WPQjcpH9R/isjyZQ9pN08ViUo7lq402VhmGblyRmH52jGb6cI3gOBKmk6etdgx/+E4zIyaZVCPppZ48a65SBMDG4gui8ZW7UP/p4NRY1s/eyB777AMDkSyoRR79t/W+0ctY7mXheSvp7uh2bh9f943e0J3wK6eA+seIQ/KBbCg/SMnLz+41tKMhPsfWyLh37cSk/b35ZndAGxJhGJSEDsdaaPUopLr8q5Mc50RNI5D8I3ZboXltmksrb1MxODlYiPNduvOSjhR9IjQm25SGcm4l3zagfl0bhV6wSgI8mnmmlzaUTFbRklKcO4OKARnGjNGpeTwE69VndwbjTBshEb64/+kZFzXfwp8T45WdzMetFG/k9lxrYAam57R8zsPX+BqZSpa4LAqV7MHXM4TjfDjlT+9mB8K/awiwk9A+ABH4uPxCZc8DvuJkS1h7Pf2sJlGWHXveIApoJiTUbGJAivq3JSHDIvwLx9Q+RZevgnRB8SMNtw9rqIdQ0/OXDDZ3vehMMC5Isrw0zDukh5CcQdQF09Q=
          on:
              repo: onivim/oni-api
    - provider: pages
      skip-cleanup: true
      local-dir: docs
      github-token:
          secure: er02MBRfBmoOMPUR6aiAh37Ok07i+t63maveLyZDXnjthaSuUXVvKpAjidHQkSbb6SctHeneb3vs85m2P/sKra132uAS2/Ko+Nt3MKMpHIYJpfeGtEBz0KKgh4U92mQV41aVTYvMnkGIbz3k89QRvruSbc3LdHK82AvgiT5r56gKsvm5srZJuWJwOCLCeWMFpD8nMgerpTMXFs2ks6WiuCJdSwrD2QijsYH1RuDo+I4Py36inEMIgOUkxzahcqSWhjSx3hABA03iKPHlO9IHhdtmMu3DiQ3eaqFkWvtU52Qz6EmtdGwrPLCjUCIQB7yGQ6PmpR2HufjCR8mO+t4NjrH10s3TQpFFxJe/qwWD+qr58d0bP2a/RJkhgegXrwKGA/zA1BQZVBkct5t7eaJFdVwKGv37Yms0fF/xJGvnSydw6M4ox2lKWNyJXyhIzDUYp7AorFQWueuwk6qH94BV9C0vhkx7QMuvHQfUDI3Yn0rTYNs3RhooKSVDiA2+s/VPPNMlKH05QE/7n3yPvhNfxpBvowdqSIXch1sD4HFO6S/D4qglygrekX2sryWt7Yoh3JYZGmw8+6D/H3pjD/1x+c8DKHBroKUOudzUciirHNEt6KRJ2/x9eBhN57s8U0+RkKbgBm0CtxaYD1WDhBOnDH3U/TOJUV/a6CgWwKhqWb0=
          keep-history: true
          on:
              branch: master

