language: node_js
node_js: 8
script:
- npm run build
deploy:
  - provider: npm
    email: bryphe@outlook.com
    skip_cleanup: true
    api_key:
      secure: R3JCd8jz8b30NO65UzTYdUwd8/j+lHxlAel9I7rtvatFLjgwQsweB1bYn76k6P09HwqXnlwsUlq2idIHcs8XdP0VruRyDzxDxsGWWTC9iyTk3WE7hd20RxQrORru9O5XhTuQ/e2e+FpRPSgFtKc+M4IrQ2jJh1jjvNlHVT/BznaQXnilKfCjGhXmk9pR35WLpSkhowWg1mfBh1VBz9bbqMHfiTOUEmEFXML1CUdEc5CTWfBJdb1/6aFAoHN+rp3zjAlFkaxHigdpZIyPFCvsUDzqC+NtqdMgTGzef1JTIrPIC+G2on/LfqE5mdzKrIIZWOWI1eKhBc0jIfEL2lVmfkGHJHTNLJtUPumlse0s3oJ2xH1y2L6Zn3iNV1k0WknUZ6VWv+dLS4x0IDaCWqy/F+xeDRirTuMYw6KTvthQlAMA3fl8b5IOsXvpV1ToIPg/O76+qvDMuj+uVvZFJmL3a7BDzOiP7H44TRSYNna6cCpmYO3JMJURYyQ+yZYBUEsw3KKcOwQp+88MAMndos7xBZKudqhddQnmA48yq2i1rJGK83SUDCS6CPsg0n1joFfPbLJ7bs7impxeGBF/3URYdCME3BH1nKy+WDUVyIGQwoRSONbDQsI0b8zUF5r1eX61t92Y3F41RBXlhgdkgkO8jcl9+VjKCrG1CQPvdIi5LG8=
    on:
      tags: true
      repo: onivim/oni-api
  - provider: pages
    skip-cleanup: true
    github-token:
        secure: er02MBRfBmoOMPUR6aiAh37Ok07i+t63maveLyZDXnjthaSuUXVvKpAjidHQkSbb6SctHeneb3vs85m2P/sKra132uAS2/Ko+Nt3MKMpHIYJpfeGtEBz0KKgh4U92mQV41aVTYvMnkGIbz3k89QRvruSbc3LdHK82AvgiT5r56gKsvm5srZJuWJwOCLCeWMFpD8nMgerpTMXFs2ks6WiuCJdSwrD2QijsYH1RuDo+I4Py36inEMIgOUkxzahcqSWhjSx3hABA03iKPHlO9IHhdtmMu3DiQ3eaqFkWvtU52Qz6EmtdGwrPLCjUCIQB7yGQ6PmpR2HufjCR8mO+t4NjrH10s3TQpFFxJe/qwWD+qr58d0bP2a/RJkhgegXrwKGA/zA1BQZVBkct5t7eaJFdVwKGv37Yms0fF/xJGvnSydw6M4ox2lKWNyJXyhIzDUYp7AorFQWueuwk6qH94BV9C0vhkx7QMuvHQfUDI3Yn0rTYNs3RhooKSVDiA2+s/VPPNMlKH05QE/7n3yPvhNfxpBvowdqSIXch1sD4HFO6S/D4qglygrekX2sryWt7Yoh3JYZGmw8+6D/H3pjD/1x+c8DKHBroKUOudzUciirHNEt6KRJ2/x9eBhN57s8U0+RkKbgBm0CtxaYD1WDhBOnDH3U/TOJUV/a6CgWwKhqWb0=
    keep-history: true
    on:
       tags: true
       branch: master
