language: node_js
node_js: 8
script:
- npm run build
deploy:
  - provider: npm
    email: bryphe@outlook.com
    skip_cleanup: true
    api_key:
      secure: JIrn6S9af2nJb4XuI3acZm9sCsubf56872a4l9KkoBO1Ej4k9zw3mEQ+nek/tceHhNtuLSJvrW5JfWDUGhSV8A9wPEvQD8CuIQUJuSOw1ybryZQmljX9gg7nlc8GKUUWbEIqDRGsXuhdhBrOset9Rmw/YgCusicqL4z6R3cMLUHeYzVxgQ4XtJgVV/UVXhXc10XbkavDrP+x4urYnzA52f3xtrJ3I2hcM6c0rnJWSTpROoCBBh+1NWXeIaCX1GIW32q+G84S50wl0SV+352NVfa5jklM+0trCfwVedqv00cpIsp7NejeGCFKLNLdGIrCCpOY5J/LG8ZsEKaEJWcyX+2C7pqerT8Z4jZuOEJqx5JDrQEil+RgDBSS0nSR0pBS6X0fLPvQYOwyRqlkj2oa2DKXQZbd/h3FaCJ/PjWRWlnpjzsjoKvnvAgpJMYlATCz9SxgOTrfigFgPlHpUkMcLcyy1T/RJrCcL7or9RmML/kpx29LuSwIQMpz7lRF5xaWit02nk3KeLTlrkstrUpgzg3S4ord7lurYrasWGywrFzdP4lhGxf8J9IBLhd+Kkkh0k8I6sTd6gM9Y2Bw71yDu7l5mQdMWsdYeamGzF4foBGany3MhSlgbvejSaYNXBHFLQRSJ2TQTKBRHgAMEgBa5XVCGhz40A1p8WFUvYfBsGA=
    on:
      repo: onivim/oni-api
  - provider: pages
    skip-cleanup: true
    local-dir: docs
    github-token:
        secure: er02MBRfBmoOMPUR6aiAh37Ok07i+t63maveLyZDXnjthaSuUXVvKpAjidHQkSbb6SctHeneb3vs85m2P/sKra132uAS2/Ko+Nt3MKMpHIYJpfeGtEBz0KKgh4U92mQV41aVTYvMnkGIbz3k89QRvruSbc3LdHK82AvgiT5r56gKsvm5srZJuWJwOCLCeWMFpD8nMgerpTMXFs2ks6WiuCJdSwrD2QijsYH1RuDo+I4Py36inEMIgOUkxzahcqSWhjSx3hABA03iKPHlO9IHhdtmMu3DiQ3eaqFkWvtU52Qz6EmtdGwrPLCjUCIQB7yGQ6PmpR2HufjCR8mO+t4NjrH10s3TQpFFxJe/qwWD+qr58d0bP2a/RJkhgegXrwKGA/zA1BQZVBkct5t7eaJFdVwKGv37Yms0fF/xJGvnSydw6M4ox2lKWNyJXyhIzDUYp7AorFQWueuwk6qH94BV9C0vhkx7QMuvHQfUDI3Yn0rTYNs3RhooKSVDiA2+s/VPPNMlKH05QE/7n3yPvhNfxpBvowdqSIXch1sD4HFO6S/D4qglygrekX2sryWt7Yoh3JYZGmw8+6D/H3pjD/1x+c8DKHBroKUOudzUciirHNEt6KRJ2/x9eBhN57s8U0+RkKbgBm0CtxaYD1WDhBOnDH3U/TOJUV/a6CgWwKhqWb0=
    keep-history: true
    on:
       branch: master
